MessageIds = {
	OBJECT_UPDATE = 1,
	OBJECT_INITIAL_ARRAY = 2,
	OBJECT_PING = 3,
	OBJECT_ACK = 4,
	OBJECT_CREATED = 5,
	OBJECT_SERVER_ID = 6,
	OBJECT_SERVER_ID_ACK = 7,
	OBJECT_DELETED = 8,
	EVENT_IDS = 9,
	EVENT = 10,
	OBJECT_CLASS_IDS = 11,
	CLIP_COEFF = 12,
	SEND_NUM_BITS = 4
}
